version: '3'

services:
  mongo: 
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: leaf
    volumes:
      - mongo:/data/db
      - ./mongo_volume:/host

volumes:
  mongo:
